### ISSUE TITLE
Auto-inject loses parameters if a class defines `initialize`

### ISSUE THREAD

**Issue by art-solopov** [dry-rb/dry-auto_inject#61] opened 2019-06-19 20:27 UTC
Here's my container.rb:

```ruby
class Container
  extend Dry::Container::Mixin

   # Some more stuff

  register(:rom, memoize: true) do
    ROM.container(Database.configuration)
  end

  # Repositories
  register(:product_repo) { ProductRepo.new(resolve(:rom)) }

  def self.import
    @import ||= Dry::AutoInject(self)
  end
end
```

And my products/create.rb:

```ruby
module Products
  class Create < ::BaseService
    include Container.import[:product_repo]

    class Contract < Dry::Validation::Contract
      params do
        required(:name).filled(:string)
        required(:price).filled(:float)
      end
    end

    attr_accessor :data, :errors

    def initialize(params)
      @params = params
    end

    # More stuff
  end
end
```

And when I try to instantiate it:

```
pry(main)> Products::Create.new({'name' => 'CoolPenz WonderPen', 'price' => 1.2})
ArgumentError: wrong number of arguments (given 2, expected 1)
```

If I replace `Container.import` with `Container.import.args`, I get this:

```
pry(main)> Products::Create.new({'name' => 'CoolPenz WonderPen', 'price' => 1.2})
=> #<Products::Create:0x0000564065c300e0 @params={"name"=>"CoolPenz WonderPen", "price"=>1.2}>
pry(main)> r.product_repo
=> nil
```

There's no exception, but the `product_repo` value isn't injected.

I use dry-auto_inject 0.6.1 and dry-container 0.7.1.

**Comment by v-kolesnikov** [comment] 2019-06-19 21:42
It's not a bug.
`include Container.import[:product_repo]` includes a module that defines `initialize` methods when it's included. You should call `super` in your constructor to make this module works

**Comment by AMHOL** [comment] 2019-06-20 01:03
> You should call super in your constructor to make this module works

You technically can do that, but probably shouldn't, the idea is to constructor inject `dependencies` and implement the behaviour of the object (the part that relies on user-input) in `#call`, so `#initialize` once, `#call` many times.

**Comment by flash-gordon** [comment] 2019-06-20 07:44
As @AMHOL said dry-auto_inject is meant to inject dependencies, using constructors for passing input data is not really what we had in mind. Pass input to `call` and treat objects with dependencies as sealed and immutable. In fact, it's not a bad idea to freeze all dependencies alongside with container when running code in production.
At the same time, it's possible to inject some extra non-registered dependencies with dry-auto_inject using the mechanism described by @v-kolesnikov 

```ruby
module Products
  class Create < ::BaseService
    include Container.import[:product_repo]

    attr_accessor :other_dep

    def initialize(other_dep, **injected_deps)
      super(injected_deps)
      @other_dep = other_dep
    end

    def call(params)
      ...
    end
  end
end
# then
Products::Create.new(MyDep.new)
```

Keep in mind that dry-v contracts return you back result objects that keep both input values and errors.
```ruby
dry-validation> result = contract { schema { required(:foo).value(:integer) } }.(foo: 'notanumber')
=> #<Dry::Validation::Result{:foo=>"notanumber"} errors={:foo=>["must be an integer"]}>
dry-validation> result.to_h
=> {:foo=>"notanumber"}
dry-validation> result.errors
=> #<Dry::Validation::MessageSet messages=[#<Dry::Schema::Message text="must be an integer" path=[:foo] predicate=:int? input="notanumber">] options={}>
```

That said, please use our forum or chat (link are in [CONTRIBUTING.md](https://github.com/dry-rb/dry-auto_inject/blob/master/CONTRIBUTING.md)) for asking for help. I'm closing this as it's not a bug.

**Closed by flash-gordon** 2019-06-20 07:44 UTC
